//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ExcelDesign.ServiceFunctions {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Functions_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Functions")]
    public partial class Functions : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchDetermineNoTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateReturnOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitiateUserActionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Functions() {
            this.Url = global::ExcelDesign.Properties.Settings.Default.ExcelDesign_ServiceFunctions_Functions;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchDetermineNoTypeCompletedEventHandler SearchDetermineNoTypeCompleted;
        
        /// <remarks/>
        public event CreateReturnOrderCompletedEventHandler CreateReturnOrderCompleted;
        
        /// <remarks/>
        public event InitiateUserActionCompletedEventHandler InitiateUserActionCompleted;
        
        /// <remarks/>
        public event CancelOrderCompletedEventHandler CancelOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Functions:SearchDetermineNoType", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", ResponseElementName="SearchDetermineNoType_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string SearchDetermineNoType(string sessionID, string searchNo, ref SearchResults searchResults) {
            object[] results = this.Invoke("SearchDetermineNoType", new object[] {
                        sessionID,
                        searchNo,
                        searchResults});
            searchResults = ((SearchResults)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchDetermineNoTypeAsync(string sessionID, string searchNo, SearchResults searchResults) {
            this.SearchDetermineNoTypeAsync(sessionID, searchNo, searchResults, null);
        }
        
        /// <remarks/>
        public void SearchDetermineNoTypeAsync(string sessionID, string searchNo, SearchResults searchResults, object userState) {
            if ((this.SearchDetermineNoTypeOperationCompleted == null)) {
                this.SearchDetermineNoTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchDetermineNoTypeOperationCompleted);
            }
            this.InvokeAsync("SearchDetermineNoType", new object[] {
                        sessionID,
                        searchNo,
                        searchResults}, this.SearchDetermineNoTypeOperationCompleted, userState);
        }
        
        private void OnSearchDetermineNoTypeOperationCompleted(object arg) {
            if ((this.SearchDetermineNoTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchDetermineNoTypeCompleted(this, new SearchDetermineNoTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Functions:CreateReturnOrder", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", ResponseElementName="CreateReturnOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CreateReturnOrder(string orderNo, string extDocNo, string returnReasonCode, int _DefectOpts, string notes, bool includeResourceLines, bool printRmaInstructions, bool createUPSReturnLabel, string lineDetails, string emailAddress) {
            object[] results = this.Invoke("CreateReturnOrder", new object[] {
                        orderNo,
                        extDocNo,
                        returnReasonCode,
                        _DefectOpts,
                        notes,
                        includeResourceLines,
                        printRmaInstructions,
                        createUPSReturnLabel,
                        lineDetails,
                        emailAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateReturnOrderAsync(string orderNo, string extDocNo, string returnReasonCode, int _DefectOpts, string notes, bool includeResourceLines, bool printRmaInstructions, bool createUPSReturnLabel, string lineDetails, string emailAddress) {
            this.CreateReturnOrderAsync(orderNo, extDocNo, returnReasonCode, _DefectOpts, notes, includeResourceLines, printRmaInstructions, createUPSReturnLabel, lineDetails, emailAddress, null);
        }
        
        /// <remarks/>
        public void CreateReturnOrderAsync(string orderNo, string extDocNo, string returnReasonCode, int _DefectOpts, string notes, bool includeResourceLines, bool printRmaInstructions, bool createUPSReturnLabel, string lineDetails, string emailAddress, object userState) {
            if ((this.CreateReturnOrderOperationCompleted == null)) {
                this.CreateReturnOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateReturnOrderOperationCompleted);
            }
            this.InvokeAsync("CreateReturnOrder", new object[] {
                        orderNo,
                        extDocNo,
                        returnReasonCode,
                        _DefectOpts,
                        notes,
                        includeResourceLines,
                        printRmaInstructions,
                        createUPSReturnLabel,
                        lineDetails,
                        emailAddress}, this.CreateReturnOrderOperationCompleted, userState);
        }
        
        private void OnCreateReturnOrderOperationCompleted(object arg) {
            if ((this.CreateReturnOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateReturnOrderCompleted(this, new CreateReturnOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Functions:InitiateUserAction", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", ResponseElementName="InitiateUserAction_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string InitiateUserAction(string sessionID, string orderNo, string extDocNo, int _ActionType, string returnReasonCode, int _DefectOpts) {
            object[] results = this.Invoke("InitiateUserAction", new object[] {
                        sessionID,
                        orderNo,
                        extDocNo,
                        _ActionType,
                        returnReasonCode,
                        _DefectOpts});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InitiateUserActionAsync(string sessionID, string orderNo, string extDocNo, int _ActionType, string returnReasonCode, int _DefectOpts) {
            this.InitiateUserActionAsync(sessionID, orderNo, extDocNo, _ActionType, returnReasonCode, _DefectOpts, null);
        }
        
        /// <remarks/>
        public void InitiateUserActionAsync(string sessionID, string orderNo, string extDocNo, int _ActionType, string returnReasonCode, int _DefectOpts, object userState) {
            if ((this.InitiateUserActionOperationCompleted == null)) {
                this.InitiateUserActionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitiateUserActionOperationCompleted);
            }
            this.InvokeAsync("InitiateUserAction", new object[] {
                        sessionID,
                        orderNo,
                        extDocNo,
                        _ActionType,
                        returnReasonCode,
                        _DefectOpts}, this.InitiateUserActionOperationCompleted, userState);
        }
        
        private void OnInitiateUserActionOperationCompleted(object arg) {
            if ((this.InitiateUserActionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitiateUserActionCompleted(this, new InitiateUserActionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Functions:CancelOrder", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", ResponseElementName="CancelOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CancelOrder(bool test) {
            object[] results = this.Invoke("CancelOrder", new object[] {
                        test});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelOrderAsync(bool test) {
            this.CancelOrderAsync(test, null);
        }
        
        /// <remarks/>
        public void CancelOrderAsync(bool test, object userState) {
            if ((this.CancelOrderOperationCompleted == null)) {
                this.CancelOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderOperationCompleted);
            }
            this.InvokeAsync("CancelOrder", new object[] {
                        test}, this.CancelOrderOperationCompleted, userState);
        }
        
        private void OnCancelOrderOperationCompleted(object arg) {
            if ((this.CancelOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderCompleted(this, new CancelOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SearchResults {
        
        private SalesHeader[] salesHeaderField;
        
        private SalesLine[] salesLineField;
        
        private SalesShipmentHeader[] salesShipmentHeaderField;
        
        private SalesShipmentLine[] salesShipmentLineField;
        
        private PostedPackage[] postedPackageField;
        
        private PostedPackageLine[] postedPackageLineField;
        
        private SalesInvoiceHeader[] salesInvoiceHeaderField;
        
        private SalesInvoiceLine[] salesInvoiceLineField;
        
        private ReturnReceiptHeader[] returnReceiptHeaderField;
        
        private ReturnReceiptLine[] returnReceiptLineField;
        
        private PostedReceive[] postedReceiveField;
        
        private PostedReceiveLine[] postedReceiveLineField;
        
        private SalesCreditMemo[] salesCreditMemoField;
        
        private SalesCreditMemoLines[] salesCreditMemoLinesField;
        
        private SOImportBuffer[] sOImportBufferField;
        
        private ReturnReasonCode[] returnReasonCodeField;
        
        private DefectOptions[] defectOptionsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesHeader")]
        public SalesHeader[] SalesHeader {
            get {
                return this.salesHeaderField;
            }
            set {
                this.salesHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesLine")]
        public SalesLine[] SalesLine {
            get {
                return this.salesLineField;
            }
            set {
                this.salesLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesShipmentHeader")]
        public SalesShipmentHeader[] SalesShipmentHeader {
            get {
                return this.salesShipmentHeaderField;
            }
            set {
                this.salesShipmentHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesShipmentLine")]
        public SalesShipmentLine[] SalesShipmentLine {
            get {
                return this.salesShipmentLineField;
            }
            set {
                this.salesShipmentLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostedPackage")]
        public PostedPackage[] PostedPackage {
            get {
                return this.postedPackageField;
            }
            set {
                this.postedPackageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostedPackageLine")]
        public PostedPackageLine[] PostedPackageLine {
            get {
                return this.postedPackageLineField;
            }
            set {
                this.postedPackageLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesInvoiceHeader")]
        public SalesInvoiceHeader[] SalesInvoiceHeader {
            get {
                return this.salesInvoiceHeaderField;
            }
            set {
                this.salesInvoiceHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesInvoiceLine")]
        public SalesInvoiceLine[] SalesInvoiceLine {
            get {
                return this.salesInvoiceLineField;
            }
            set {
                this.salesInvoiceLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnReceiptHeader")]
        public ReturnReceiptHeader[] ReturnReceiptHeader {
            get {
                return this.returnReceiptHeaderField;
            }
            set {
                this.returnReceiptHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnReceiptLine")]
        public ReturnReceiptLine[] ReturnReceiptLine {
            get {
                return this.returnReceiptLineField;
            }
            set {
                this.returnReceiptLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostedReceive")]
        public PostedReceive[] PostedReceive {
            get {
                return this.postedReceiveField;
            }
            set {
                this.postedReceiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostedReceiveLine")]
        public PostedReceiveLine[] PostedReceiveLine {
            get {
                return this.postedReceiveLineField;
            }
            set {
                this.postedReceiveLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesCreditMemo")]
        public SalesCreditMemo[] SalesCreditMemo {
            get {
                return this.salesCreditMemoField;
            }
            set {
                this.salesCreditMemoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesCreditMemoLines")]
        public SalesCreditMemoLines[] SalesCreditMemoLines {
            get {
                return this.salesCreditMemoLinesField;
            }
            set {
                this.salesCreditMemoLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SOImportBuffer")]
        public SOImportBuffer[] SOImportBuffer {
            get {
                return this.sOImportBufferField;
            }
            set {
                this.sOImportBufferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnReasonCode")]
        public ReturnReasonCode[] ReturnReasonCode {
            get {
                return this.returnReasonCodeField;
            }
            set {
                this.returnReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefectOptions")]
        public DefectOptions[] DefectOptions {
            get {
                return this.defectOptionsField;
            }
            set {
                this.defectOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesHeader {
        
        private string docTypeField;
        
        private string noField;
        
        private string extDocNoField;
        
        private string docDateField;
        
        private string returnTrackingNoField;
        
        private string sellToCustomerNameField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        private Warranty2[] warranty2Field;
        
        /// <remarks/>
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDocNo {
            get {
                return this.extDocNoField;
            }
            set {
                this.extDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string DocDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnTrackingNo {
            get {
                return this.returnTrackingNoField;
            }
            set {
                this.returnTrackingNoField = value;
            }
        }
        
        /// <remarks/>
        public string SellToCustomerName {
            get {
                return this.sellToCustomerNameField;
            }
            set {
                this.sellToCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warranty2")]
        public Warranty2[] Warranty2 {
            get {
                return this.warranty2Field;
            }
            set {
                this.warranty2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class Warranty2 {
        
        private string[] status2Field;
        
        private string[] policy2Field;
        
        private string[] daysRemaining2Field;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status2")]
        public string[] Status2 {
            get {
                return this.status2Field;
            }
            set {
                this.status2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Policy2")]
        public string[] Policy2 {
            get {
                return this.policy2Field;
            }
            set {
                this.policy2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DaysRemaining2")]
        public string[] DaysRemaining2 {
            get {
                return this.daysRemaining2Field;
            }
            set {
                this.daysRemaining2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class DefectOptions {
        
        private string[] blankField;
        
        private string[] noLongerWantedField;
        
        private string[] pWrongNetworkField;
        
        private string[] notAsExpectedField;
        
        private string[] shippingBoxChrushedField;
        
        private string[] phoneBoxChrushedField;
        
        private string[] packageWetField;
        
        private string[] unresponsiveLCDField;
        
        private string[] doesNotChargeField;
        
        private string[] badKeypadField;
        
        private string[] badMicEarpieceSpeakerField;
        
        private string[] noPowerField;
        
        private string[] noWIfiField;
        
        private string[] noSignalField;
        
        private string[] resetsItselfField;
        
        private string[] badCameraField;
        
        private string[] callsDroppedField;
        
        private string[] doesNotReadSIMField;
        
        private string[] doesNotReadSDField;
        
        private string[] phoneIsLockedField;
        
        private string[] wrongBandsListedField;
        
        private string[] wrongColorModelField;
        
        private string[] cantSetupMMSField;
        
        private string[] notInEnglishField;
        
        private string[] uSedCustomerInfoField;
        
        private string[] usedCallTimerField;
        
        private string[] usedAccessoriesField;
        
        private string[] usedScratehcesDentsDingsField;
        
        private string[] boxNotSealedField;
        
        private string[] softwareField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Blank")]
        public string[] Blank {
            get {
                return this.blankField;
            }
            set {
                this.blankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoLongerWanted")]
        public string[] NoLongerWanted {
            get {
                return this.noLongerWantedField;
            }
            set {
                this.noLongerWantedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PWrongNetwork")]
        public string[] PWrongNetwork {
            get {
                return this.pWrongNetworkField;
            }
            set {
                this.pWrongNetworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NotAsExpected")]
        public string[] NotAsExpected {
            get {
                return this.notAsExpectedField;
            }
            set {
                this.notAsExpectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShippingBoxChrushed")]
        public string[] ShippingBoxChrushed {
            get {
                return this.shippingBoxChrushedField;
            }
            set {
                this.shippingBoxChrushedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneBoxChrushed")]
        public string[] PhoneBoxChrushed {
            get {
                return this.phoneBoxChrushedField;
            }
            set {
                this.phoneBoxChrushedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageWet")]
        public string[] PackageWet {
            get {
                return this.packageWetField;
            }
            set {
                this.packageWetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnresponsiveLCD")]
        public string[] UnresponsiveLCD {
            get {
                return this.unresponsiveLCDField;
            }
            set {
                this.unresponsiveLCDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoesNotCharge")]
        public string[] DoesNotCharge {
            get {
                return this.doesNotChargeField;
            }
            set {
                this.doesNotChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BadKeypad")]
        public string[] BadKeypad {
            get {
                return this.badKeypadField;
            }
            set {
                this.badKeypadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BadMicEarpieceSpeaker")]
        public string[] BadMicEarpieceSpeaker {
            get {
                return this.badMicEarpieceSpeakerField;
            }
            set {
                this.badMicEarpieceSpeakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoPower")]
        public string[] NoPower {
            get {
                return this.noPowerField;
            }
            set {
                this.noPowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoWIfi")]
        public string[] NoWIfi {
            get {
                return this.noWIfiField;
            }
            set {
                this.noWIfiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSignal")]
        public string[] NoSignal {
            get {
                return this.noSignalField;
            }
            set {
                this.noSignalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResetsItself")]
        public string[] ResetsItself {
            get {
                return this.resetsItselfField;
            }
            set {
                this.resetsItselfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BadCamera")]
        public string[] BadCamera {
            get {
                return this.badCameraField;
            }
            set {
                this.badCameraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CallsDropped")]
        public string[] CallsDropped {
            get {
                return this.callsDroppedField;
            }
            set {
                this.callsDroppedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoesNotReadSIM")]
        public string[] DoesNotReadSIM {
            get {
                return this.doesNotReadSIMField;
            }
            set {
                this.doesNotReadSIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DoesNotReadSD")]
        public string[] DoesNotReadSD {
            get {
                return this.doesNotReadSDField;
            }
            set {
                this.doesNotReadSDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneIsLocked")]
        public string[] PhoneIsLocked {
            get {
                return this.phoneIsLockedField;
            }
            set {
                this.phoneIsLockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WrongBandsListed")]
        public string[] WrongBandsListed {
            get {
                return this.wrongBandsListedField;
            }
            set {
                this.wrongBandsListedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WrongColorModel")]
        public string[] WrongColorModel {
            get {
                return this.wrongColorModelField;
            }
            set {
                this.wrongColorModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CantSetupMMS")]
        public string[] CantSetupMMS {
            get {
                return this.cantSetupMMSField;
            }
            set {
                this.cantSetupMMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NotInEnglish")]
        public string[] NotInEnglish {
            get {
                return this.notInEnglishField;
            }
            set {
                this.notInEnglishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USedCustomerInfo")]
        public string[] USedCustomerInfo {
            get {
                return this.uSedCustomerInfoField;
            }
            set {
                this.uSedCustomerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsedCallTimer")]
        public string[] UsedCallTimer {
            get {
                return this.usedCallTimerField;
            }
            set {
                this.usedCallTimerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsedAccessories")]
        public string[] UsedAccessories {
            get {
                return this.usedAccessoriesField;
            }
            set {
                this.usedAccessoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsedScratehcesDentsDings")]
        public string[] UsedScratehcesDentsDings {
            get {
                return this.usedScratehcesDentsDingsField;
            }
            set {
                this.usedScratehcesDentsDingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoxNotSealed")]
        public string[] BoxNotSealed {
            get {
                return this.boxNotSealedField;
            }
            set {
                this.boxNotSealedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Software")]
        public string[] Software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class ReturnReasonCode {
        
        private string reasonCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class Warranty {
        
        private string[] statusField;
        
        private string[] policyField;
        
        private string[] daysRemainingField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public string[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Policy")]
        public string[] Policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DaysRemaining")]
        public string[] DaysRemaining {
            get {
                return this.daysRemainingField;
            }
            set {
                this.daysRemainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SOImportBuffer {
        
        private string externalDocumentNoField;
        
        private string orderTypeField;
        
        private string orderStatusField;
        
        private string orderDateField;
        
        private string salesOrderNoField;
        
        private string[] channelNameField;
        
        private string customerNoField;
        
        private string qtyField;
        
        private string priceField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        private Warranty[] warrantyField;
        
        /// <remarks/>
        public string ExternalDocumentNo {
            get {
                return this.externalDocumentNoField;
            }
            set {
                this.externalDocumentNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string SalesOrderNo {
            get {
                return this.salesOrderNoField;
            }
            set {
                this.salesOrderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChannelName")]
        public string[] ChannelName {
            get {
                return this.channelNameField;
            }
            set {
                this.channelNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warranty")]
        public Warranty[] Warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesCreditMemoLines {
        
        private string docNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string unitPriceField;
        
        /// <remarks/>
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesCreditMemo {
        
        private string noField;
        
        private string extDocNoField;
        
        private string postingDateField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDocNo {
            get {
                return this.extDocNoField;
            }
            set {
                this.extDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class PostedReceiveLine {
        
        private string recNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string serialNoField;
        
        /// <remarks/>
        public string RecNo {
            get {
                return this.recNoField;
            }
            set {
                this.recNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class PostedReceive {
        
        private string noField;
        
        private string extDocNoField;
        
        private string extTrackNoField;
        
        private string shippingAgentField;
        
        private string shippingServiceField;
        
        private string receiveDateField;
        
        private string postedSourceIDField;
        
        private string sourceIDField;
        
        private string shipFromNameField;
        
        private string shipFromAddressField;
        
        private string shipFromAddress2Field;
        
        private string shipFromContactField;
        
        private string shipFromCityField;
        
        private string shipFromZipField;
        
        private string shipFromStateField;
        
        private string shipFromCountryField;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDocNo {
            get {
                return this.extDocNoField;
            }
            set {
                this.extDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string ExtTrackNo {
            get {
                return this.extTrackNoField;
            }
            set {
                this.extTrackNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingAgent {
            get {
                return this.shippingAgentField;
            }
            set {
                this.shippingAgentField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingService {
            get {
                return this.shippingServiceField;
            }
            set {
                this.shippingServiceField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string PostedSourceID {
            get {
                return this.postedSourceIDField;
            }
            set {
                this.postedSourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromName {
            get {
                return this.shipFromNameField;
            }
            set {
                this.shipFromNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromAddress {
            get {
                return this.shipFromAddressField;
            }
            set {
                this.shipFromAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromAddress2 {
            get {
                return this.shipFromAddress2Field;
            }
            set {
                this.shipFromAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromContact {
            get {
                return this.shipFromContactField;
            }
            set {
                this.shipFromContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromCity {
            get {
                return this.shipFromCityField;
            }
            set {
                this.shipFromCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromZip {
            get {
                return this.shipFromZipField;
            }
            set {
                this.shipFromZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromState {
            get {
                return this.shipFromStateField;
            }
            set {
                this.shipFromStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromCountry {
            get {
                return this.shipFromCountryField;
            }
            set {
                this.shipFromCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class ReturnReceiptLine {
        
        private string docNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string unitPriceField;
        
        /// <remarks/>
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class ReturnReceiptHeader {
        
        private string noField;
        
        private string extDocNoField;
        
        private string receiveDateField;
        
        private string orderDateField;
        
        private string returnOrderNoField;
        
        private string shippingAgentField;
        
        private string sellToCustomerNoField;
        
        private string sellToCustomerNameField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDocNo {
            get {
                return this.extDocNoField;
            }
            set {
                this.extDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnOrderNo {
            get {
                return this.returnOrderNoField;
            }
            set {
                this.returnOrderNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingAgent {
            get {
                return this.shippingAgentField;
            }
            set {
                this.shippingAgentField = value;
            }
        }
        
        /// <remarks/>
        public string SellToCustomerNo {
            get {
                return this.sellToCustomerNoField;
            }
            set {
                this.sellToCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string SellToCustomerName {
            get {
                return this.sellToCustomerNameField;
            }
            set {
                this.sellToCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesInvoiceLine {
        
        private string docNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string unitPriceField;
        
        /// <remarks/>
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesInvoiceHeader {
        
        private string noField;
        
        private string extDocNoField;
        
        private string postingDateField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDocNo {
            get {
                return this.extDocNoField;
            }
            set {
                this.extDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class PostedPackageLine {
        
        private string packNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string priceField;
        
        private string serialNoField;
        
        /// <remarks/>
        public string PackNo {
            get {
                return this.packNoField;
            }
            set {
                this.packNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class PostedPackage {
        
        private string packNoField;
        
        private string extTrackNoField;
        
        private string shippingAgentField;
        
        private string shippingServiceField;
        
        private string postingDateField;
        
        private string postedSourceIDField;
        
        private string sourceIDField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        /// <remarks/>
        public string PackNo {
            get {
                return this.packNoField;
            }
            set {
                this.packNoField = value;
            }
        }
        
        /// <remarks/>
        public string ExtTrackNo {
            get {
                return this.extTrackNoField;
            }
            set {
                this.extTrackNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingAgent {
            get {
                return this.shippingAgentField;
            }
            set {
                this.shippingAgentField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingService {
            get {
                return this.shippingServiceField;
            }
            set {
                this.shippingServiceField = value;
            }
        }
        
        /// <remarks/>
        public string PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
        
        /// <remarks/>
        public string PostedSourceID {
            get {
                return this.postedSourceIDField;
            }
            set {
                this.postedSourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesShipmentLine {
        
        private string docNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string unitPriceField;
        
        /// <remarks/>
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class Warranty3 {
        
        private string[] status3Field;
        
        private string[] policy3Field;
        
        private string[] daysRemaining3Field;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status3")]
        public string[] Status3 {
            get {
                return this.status3Field;
            }
            set {
                this.status3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Policy3")]
        public string[] Policy3 {
            get {
                return this.policy3Field;
            }
            set {
                this.policy3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DaysRemaining3")]
        public string[] DaysRemaining3 {
            get {
                return this.daysRemaining3Field;
            }
            set {
                this.daysRemaining3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesShipmentHeader {
        
        private string noField;
        
        private string extDocNoField;
        
        private string shippingDateField;
        
        private string orderDateField;
        
        private string orderNoField;
        
        private string sellToCustomerNoField;
        
        private string shipToNameField;
        
        private string shipToAddressField;
        
        private string shipToAddress2Field;
        
        private string shipToContactField;
        
        private string shipToCityField;
        
        private string shipToZipField;
        
        private string shipToStateField;
        
        private string shipToCountryField;
        
        private string shippingAgentCodeField;
        
        private string shippingAgentServiceField;
        
        private Warranty3[] warranty3Field;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDocNo {
            get {
                return this.extDocNoField;
            }
            set {
                this.extDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingDate {
            get {
                return this.shippingDateField;
            }
            set {
                this.shippingDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string SellToCustomerNo {
            get {
                return this.sellToCustomerNoField;
            }
            set {
                this.sellToCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToContact {
            get {
                return this.shipToContactField;
            }
            set {
                this.shipToContactField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingAgentCode {
            get {
                return this.shippingAgentCodeField;
            }
            set {
                this.shippingAgentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingAgentService {
            get {
                return this.shippingAgentServiceField;
            }
            set {
                this.shippingAgentServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warranty3")]
        public Warranty3[] Warranty3 {
            get {
                return this.warranty3Field;
            }
            set {
                this.warranty3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="<urn:microsoft-dynamics-nav/xmlports/searchresults>")]
    public partial class SalesLine {
        
        private string docNoField;
        
        private string typeField;
        
        private string itemNoField;
        
        private string descriptionField;
        
        private string qtyField;
        
        private string qtyToReceiveField;
        
        private string qtyShippedField;
        
        private string unitPriceField;
        
        private string dateCreatedField;
        
        /// <remarks/>
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string QtyToReceive {
            get {
                return this.qtyToReceiveField;
            }
            set {
                this.qtyToReceiveField = value;
            }
        }
        
        /// <remarks/>
        public string QtyShipped {
            get {
                return this.qtyShippedField;
            }
            set {
                this.qtyShippedField = value;
            }
        }
        
        /// <remarks/>
        public string UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public string DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchDetermineNoTypeCompletedEventHandler(object sender, SearchDetermineNoTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchDetermineNoTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchDetermineNoTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public SearchResults searchResults {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResults)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateReturnOrderCompletedEventHandler(object sender, CreateReturnOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateReturnOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateReturnOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InitiateUserActionCompletedEventHandler(object sender, InitiateUserActionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitiateUserActionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitiateUserActionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CancelOrderCompletedEventHandler(object sender, CancelOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591